/**
 * Discoverify-style recommendation pipeline (ported from spotifyHelper.js).
 * Tries GET /recommendations first; falls back to related-artists + top-tracks.
 */
import { pickTracksViaRelatedArtists } from './fallback'
import { spotifyFetch, spotifyPost, spotifyPut } from '../spotify/api'
import type { SpotifyPlaylist, SpotifyTrack } from '../spotify/types'
import {
  loadDiscoverPlaylistId,
  saveDiscoverPlaylistId,
  type PlaylistOptions,
  type SeedCode,
} from './options'

const PLAYLIST_NAME = 'Niche Daily'
const PLAYLIST_DESCRIPTION =
  'Daily music curated from your listening history — generated by Niche.'
const PLAYLIST_SIZE = 30

type TimeRange = 'short_term' | 'medium_term' | 'long_term'

interface TopPools {
  allTime: { artists: string[] | null; tracks: string[] | null }
  mediumTerm: { artists: string[] | null; tracks: string[] | null }
  shortTerm: { artists: string[] | null; tracks: string[] | null }
}

interface RecommendationTrack {
  id: string
  uri: string
}

interface RecommendationsResponse {
  tracks: RecommendationTrack[]
}

async function getTop(
  type: 'artists' | 'tracks',
  range: TimeRange
): Promise<string[]> {
  const result = await spotifyFetch<{ items: { id: string }[] }>(
    `/me/top/${type}?limit=20&time_range=${range}`
  )
  return result.items.map((x) => x.id)
}

async function getAllTop(options: PlaylistOptions): Promise<TopPools> {
  const { seeds } = options
  return {
    allTime: {
      artists: seeds.includes('AA') ? await getTop('artists', 'long_term') : null,
      tracks: seeds.includes('AT') ? await getTop('tracks', 'long_term') : null,
    },
    mediumTerm: {
      artists: seeds.includes('MA')
        ? await getTop('artists', 'medium_term')
        : null,
      tracks: seeds.includes('MT') ? await getTop('tracks', 'medium_term') : null,
    },
    shortTerm: {
      artists: seeds.includes('SA') ? await getTop('artists', 'short_term') : null,
      tracks: seeds.includes('ST') ? await getTop('tracks', 'short_term') : null,
    },
  }
}

function pickRandom(pool: string[] | null): string | null {
  if (!pool?.length) return null
  const index = Math.floor(Math.random() * pool.length)
  return pool.splice(index, 1)[0] ?? null
}

/** Random seed IDs from top listening pools (discoverify getSeeds). */
function getSeeds(options: PlaylistOptions, top: TopPools): {
  artists: string[]
  tracks: string[]
} {
  const artists: string[] = []
  const tracks: string[] = []

  const pools = {
    allTime: {
      artists: top.allTime.artists ? [...top.allTime.artists] : null,
      tracks: top.allTime.tracks ? [...top.allTime.tracks] : null,
    },
    mediumTerm: {
      artists: top.mediumTerm.artists ? [...top.mediumTerm.artists] : null,
      tracks: top.mediumTerm.tracks ? [...top.mediumTerm.tracks] : null,
    },
    shortTerm: {
      artists: top.shortTerm.artists ? [...top.shortTerm.artists] : null,
      tracks: top.shortTerm.tracks ? [...top.shortTerm.tracks] : null,
    },
  }

  for (const code of options.seeds) {
    switch (code) {
      case 'AT': {
        const id = pickRandom(pools.allTime.tracks)
        if (id) tracks.push(id)
        break
      }
      case 'MT': {
        const id = pickRandom(pools.mediumTerm.tracks)
        if (id) tracks.push(id)
        break
      }
      case 'ST': {
        const id = pickRandom(pools.shortTerm.tracks)
        if (id) tracks.push(id)
        break
      }
      case 'AA': {
        const id = pickRandom(pools.allTime.artists)
        if (id) artists.push(id)
        break
      }
      case 'MA': {
        const id = pickRandom(pools.mediumTerm.artists)
        if (id) artists.push(id)
        break
      }
      case 'SA': {
        const id = pickRandom(pools.shortTerm.artists)
        if (id) artists.push(id)
        break
      }
      default:
        throw new Error(`Unknown seed code: ${code as SeedCode}`)
    }
  }

  return { artists, tracks }
}

function getRecommendationUrls(
  options: PlaylistOptions,
  seeds: { artists: string[]; tracks: string[] }
): { minMaxUrl: string; targetUrl: string } {
  const params = new URLSearchParams({ limit: '50' })
  if (seeds.artists.length) params.set('seed_artists', seeds.artists.join(','))
  if (seeds.tracks.length) params.set('seed_tracks', seeds.tracks.join(','))

  const minMax = new URLSearchParams(params)
  const setRange = (key: string, range: [number, number], scale = 100) => {
    minMax.set(`min_${key}`, String(range[0] / scale))
    minMax.set(`max_${key}`, String(range[1] / scale))
  }
  setRange('acousticness', options.acousticness)
  setRange('danceability', options.danceability)
  setRange('energy', options.energy)
  setRange('instrumentalness', options.instrumentalness)
  minMax.set('min_popularity', String(options.popularity[0]))
  minMax.set('max_popularity', String(options.popularity[1]))
  setRange('valence', options.valence)

  const target = new URLSearchParams(params)
  const setTarget = (key: string, range: [number, number], scale = 100) => {
    target.set(`target_${key}`, String((range[0] + range[1]) / (2 * scale)))
  }
  setTarget('acousticness', options.acousticness)
  setTarget('danceability', options.danceability)
  setTarget('energy', options.energy)
  setTarget('instrumentalness', options.instrumentalness)
  target.set(
    'target_popularity',
    String(Math.round((options.popularity[0] + options.popularity[1]) / 2))
  )
  setTarget('valence', options.valence)

  return {
    minMaxUrl: `/recommendations?${minMax}`,
    targetUrl: `/recommendations?${target}`,
  }
}

async function getLiked(trackIds: string[]): Promise<boolean[]> {
  if (!trackIds.length) return []
  return spotifyFetch<boolean[]>(
    `/me/tracks/contains?ids=${trackIds.join(',')}`
  )
}

function isRecommendationsUnavailable(err: unknown): boolean {
  if (!(err instanceof Error)) return false
  return (
    /404/.test(err.message) ||
    /recommendations/i.test(err.message) ||
    /not found/i.test(err.message)
  )
}

async function fetchRecommendations(
  path: string
): Promise<RecommendationTrack[] | null> {
  try {
    let response = await spotifyFetch<RecommendationsResponse>(path)
    if (!response.tracks?.length) {
      await new Promise((r) => setTimeout(r, 1000))
      response = await spotifyFetch<RecommendationsResponse>(path)
    }
    return response.tracks ?? []
  } catch (e) {
    if (isRecommendationsUnavailable(e)) return null
    throw e
  }
}

/** Pick 30 track URIs via discoverify recommendations API. */
async function pickPlaylistUrisViaRecommendations(
  options: PlaylistOptions,
  seeds: { artists: string[]; tracks: string[] },
  tracksInPlaylist: Set<string>
): Promise<string[] | null> {
  const { minMaxUrl, targetUrl } = getRecommendationUrls(options, seeds)

  const collectFromResponse = async (
    path: string,
    playlistUris: Set<string>,
    likedTracks: Set<string>,
    alreadyInPlaylist: Set<string>
  ) => {
    const tracks = await fetchRecommendations(path)
    if (!tracks?.length) return
    const trackIds: string[] = []
    const uris: string[] = []
    for (const t of tracks) {
      trackIds.push(t.id)
      uris.push(t.uri)
    }

    const liked = await getLiked(trackIds)
    for (let i = 0; i < liked.length; i += 1) {
      if (!liked[i]) playlistUris.add(uris[i]!)
      else likedTracks.add(uris[i]!)

      if (tracksInPlaylist.has(trackIds[i]!)) alreadyInPlaylist.add(uris[i]!)

      if (playlistUris.size >= PLAYLIST_SIZE) break
    }
  }

  const playlistUris = new Set<string>()
  const likedTracks = new Set<string>()
  const alreadyInPlaylist = new Set<string>()

  await collectFromResponse(minMaxUrl, playlistUris, likedTracks, alreadyInPlaylist)

  if (playlistUris.size < PLAYLIST_SIZE) {
    await collectFromResponse(targetUrl, playlistUris, likedTracks, alreadyInPlaylist)
  }

  for (const track of alreadyInPlaylist) {
    if (playlistUris.size >= PLAYLIST_SIZE) break
    if (!likedTracks.has(track)) playlistUris.add(track)
  }

  for (const track of likedTracks) {
    if (playlistUris.size >= PLAYLIST_SIZE) break
    playlistUris.add(track)
  }

  return playlistUris.size > 0 ? Array.from(playlistUris) : null
}

async function pickPlaylistUris(
  options: PlaylistOptions,
  seeds: { artists: string[]; tracks: string[] },
  tracksInPlaylist: Set<string>,
  market: string
): Promise<{ uris: string[]; mode: 'recommendations' | 'related-artists' }> {
  const fromApi = await pickPlaylistUrisViaRecommendations(
    options,
    seeds,
    tracksInPlaylist
  )
  if (fromApi?.length) {
    return { uris: fromApi, mode: 'recommendations' }
  }

  const fallback = await pickTracksViaRelatedArtists(
    seeds,
    options,
    tracksInPlaylist,
    market
  )
  return { uris: fallback, mode: 'related-artists' }
}

async function findOwnedPlaylist(
  userId: string,
  playlistId: string | null
): Promise<SpotifyPlaylist | null> {
  if (!playlistId) return null
  try {
    const playlist = await spotifyFetch<SpotifyPlaylist>(`/playlists/${playlistId}`)
    return playlist.owner?.id === userId ? playlist : null
  } catch {
    return null
  }
}

type PlaylistListPage = {
  items: (SpotifyPlaylist | null)[] | null
  next: string | null
}

type PlaylistTracksListPage = {
  items: { track: SpotifyTrack | null }[]
  next: string | null
}

async function playlistExistsInLibrary(playlistId: string): Promise<boolean> {
  let url: string | null = '/me/playlists?limit=50'
  while (url) {
    const path: string = url.startsWith('http')
      ? url.replace('https://api.spotify.com/v1', '')
      : url
    const page: PlaylistListPage = await spotifyFetch<PlaylistListPage>(path)
    for (const p of page.items ?? []) {
      if (p?.id === playlistId) return true
    }
    url = page.next ? page.next.replace('https://api.spotify.com/v1', '') : null
  }
  return false
}

async function createDiscoverPlaylist(userId: string): Promise<string> {
  const created = await spotifyPost<{ id: string }>(
    `/users/${userId}/playlists`,
    {
      name: PLAYLIST_NAME,
      public: false,
      description: PLAYLIST_DESCRIPTION,
    }
  )
  return created.id
}

async function replacePlaylistTracks(
  playlistId: string,
  uris: string[]
): Promise<void> {
  await spotifyPut(`/playlists/${playlistId}/tracks`, { uris })
}

export interface GenerateResult {
  playlistId: string
  trackCount: number
  playlistUrl: string
  mode: 'recommendations' | 'related-artists'
}

/** Full discoverify-style update: seeds → recommendations → write playlist. */
export async function generateDiscoverPlaylist(
  userId: string,
  options: PlaylistOptions,
  market = 'US'
): Promise<GenerateResult> {
  if (!options.seeds.length) {
    throw new Error('Add at least one seed.')
  }
  if (options.seeds.length > 5) {
    throw new Error('Spotify allows at most 5 seeds. Use 5 slots or fewer.')
  }

  const top = await getAllTop(options)
  const seeds = getSeeds(options, top)

  if (!seeds.artists.length && !seeds.tracks.length) {
    throw new Error(
      'Could not build seeds from your listening history. Try different seed types or listen to more music on Spotify.'
    )
  }

  let playlistId = loadDiscoverPlaylistId()
  let playlist = await findOwnedPlaylist(userId, playlistId)

  if (!playlist || !(await playlistExistsInLibrary(playlistId!))) {
    playlistId = await createDiscoverPlaylist(userId)
    saveDiscoverPlaylistId(playlistId)
    playlist = await spotifyFetch<SpotifyPlaylist>(`/playlists/${playlistId}`)
  }

  const existingIds = new Set<string>()
  if (playlist) {
    let url: string | null = `/playlists/${playlistId}/tracks?limit=50`
    while (url) {
      const path: string = url.startsWith('http')
        ? url.replace('https://api.spotify.com/v1', '')
        : url
      const page: PlaylistTracksListPage =
        await spotifyFetch<PlaylistTracksListPage>(path)
      for (const item of page.items ?? []) {
        if (item.track?.id) existingIds.add(item.track.id)
      }
      url = page.next ? page.next.replace('https://api.spotify.com/v1', '') : null
    }
  }

  const { uris, mode } = await pickPlaylistUris(
    options,
    seeds,
    existingIds,
    market
  )
  if (!uris.length) {
    throw new Error(
      mode === 'related-artists'
        ? 'No tracks found via related artists. Try different seeds or widen the popularity range.'
        : 'No tracks matched your settings. Widen the mood sliders or change seeds.'
    )
  }

  await replacePlaylistTracks(playlistId!, uris)

  const updated = await spotifyFetch<SpotifyPlaylist>(`/playlists/${playlistId}`)
  return {
    playlistId: playlistId!,
    trackCount: uris.length,
    playlistUrl: updated.external_urls.spotify,
    mode,
  }
}
