/**
 * Niche Daily: genre-based artist discovery → one top track per artist.
 */
import { pickPlaylistFromNicheArtists } from './artistDiscover'
import { fetchKnownArtistIds } from './knownArtists'
import {
  loadDiscoverPlaylistId,
  saveDiscoverPlaylistId,
  type PlaylistOptions,
} from './options'
import { spotifyFetch, spotifyPost, spotifyPut } from '../spotify/api'
import type { SpotifyPlaylist } from '../spotify/types'

const PLAYLIST_NAME = 'Niche Daily'
const PLAYLIST_DESCRIPTION =
  'Daily niche artists in your genres — one standout track each. Generated by Niche.'

async function findOwnedPlaylist(
  userId: string,
  playlistId: string | null
): Promise<SpotifyPlaylist | null> {
  if (!playlistId) return null
  try {
    const playlist = await spotifyFetch<SpotifyPlaylist>(`/playlists/${playlistId}`)
    return playlist.owner?.id === userId ? playlist : null
  } catch {
    return null
  }
}

type PlaylistListPage = {
  items: (SpotifyPlaylist | null)[] | null
  next: string | null
}

async function playlistExistsInLibrary(playlistId: string): Promise<boolean> {
  let url: string | null = '/me/playlists?limit=50'
  while (url) {
    const path: string = url.startsWith('http')
      ? url.replace('https://api.spotify.com/v1', '')
      : url
    const page = await spotifyFetch<PlaylistListPage>(path)
    for (const p of page.items ?? []) {
      if (p?.id === playlistId) return true
    }
    url = page.next ? page.next.replace('https://api.spotify.com/v1', '') : null
  }
  return false
}

async function createDiscoverPlaylist(userId: string): Promise<string> {
  const created = await spotifyPost<{ id: string }>(
    `/users/${userId}/playlists`,
    {
      name: PLAYLIST_NAME,
      public: false,
      description: PLAYLIST_DESCRIPTION,
    }
  )
  return created.id
}

async function replacePlaylistTracks(
  playlistId: string,
  uris: string[]
): Promise<void> {
  await spotifyPut(`/playlists/${playlistId}/tracks`, { uris })
}

export type DiscoverMode = 'niche-artists'

export interface GenerateResult {
  playlistId: string
  trackCount: number
  playlistUrl: string
  mode: DiscoverMode
  artistCount: number
  targetGenres: string[]
}

export async function generateDiscoverPlaylist(
  userId: string,
  options: PlaylistOptions,
  market = 'US'
): Promise<GenerateResult> {
  if (!options.genres.length && !options.anchorArtistIds.length) {
    throw new Error(
      'Add genres (e.g. country, edm) and/or anchor artist Spotify IDs.'
    )
  }

  let playlistId = loadDiscoverPlaylistId()
  const playlist = await findOwnedPlaylist(userId, playlistId)

  if (!playlist || !(await playlistExistsInLibrary(playlistId!))) {
    playlistId = await createDiscoverPlaylist(userId)
    saveDiscoverPlaylistId(playlistId)
  }

  const knownArtistIds = await fetchKnownArtistIds()

  const { uris, artistCount, targetGenres } = await pickPlaylistFromNicheArtists(
    options,
    knownArtistIds,
    market
  )

  await replacePlaylistTracks(playlistId!, uris)

  const updated = await spotifyFetch<SpotifyPlaylist>(`/playlists/${playlistId}`)
  return {
    playlistId: playlistId!,
    trackCount: uris.length,
    playlistUrl: updated.external_urls.spotify,
    mode: 'niche-artists',
    artistCount,
    targetGenres,
  }
}
