/**
 * Niche Daily: genre-based artist discovery → one top track per artist.
 */
import { pickPlaylistFromNicheArtists } from './artistDiscover.js'
import { spotifyFetch, spotifyPost, spotifyPut } from './spotify.js'
import type { PlaylistOptions } from '../discover/options.js'

const PLAYLIST_NAME = 'Niche Daily'
const PLAYLIST_DESCRIPTION =
  'Daily niche artists in your genres — one standout track each. Generated by Niche.'
const PLAYLIST_SIZE = 30

interface SpotifyPlaylist {
  id: string
  owner?: { id: string }
  external_urls: { spotify: string }
}

async function findOwnedPlaylist(
  userId: string,
  playlistId: string | null,
  accessToken: string
): Promise<SpotifyPlaylist | null> {
  if (!playlistId) return null
  try {
    const playlist = await spotifyFetch<SpotifyPlaylist>(
      `/playlists/${playlistId}`,
      accessToken
    )
    return playlist.owner?.id === userId ? playlist : null
  } catch {
    return null
  }
}

type PlaylistListPage = {
  items: (SpotifyPlaylist | null)[] | null
  next: string | null
}

async function playlistExistsInLibrary(
  playlistId: string,
  accessToken: string
): Promise<boolean> {
  let url: string | null = '/me/playlists?limit=50'
  while (url) {
    const path: string = url.startsWith('http')
      ? url.replace('https://api.spotify.com/v1', '')
      : url
    const page = await spotifyFetch<PlaylistListPage>(path, accessToken)
    for (const p of page.items ?? []) {
      if (p?.id === playlistId) return true
    }
    url = page.next ? page.next.replace('https://api.spotify.com/v1', '') : null
  }
  return false
}

async function createDiscoverPlaylist(
  userId: string,
  accessToken: string
): Promise<string> {
  const created = await spotifyPost<{ id: string }>(
    `/users/${userId}/playlists`,
    accessToken,
    {
      name: PLAYLIST_NAME,
      public: false,
      description: PLAYLIST_DESCRIPTION,
    }
  )
  return created.id
}

async function replacePlaylistTracks(
  playlistId: string,
  uris: string[],
  accessToken: string
): Promise<void> {
  await spotifyPut(`/playlists/${playlistId}/tracks`, accessToken, { uris })
}

export type DiscoverMode = 'niche-artists'

export interface GenerateResult {
  playlistId: string
  trackCount: number
  playlistUrl: string
  mode: DiscoverMode
  artistCount: number
  targetGenres: string[]
}

export async function generateDiscoverPlaylist(
  userId: string,
  options: PlaylistOptions,
  accessToken: string,
  market = 'US',
  storedPlaylistId: string | null = null,
  knownArtistIds?: Set<string>
): Promise<GenerateResult> {
  if (!options.genres.length && !options.anchorArtistIds.length) {
    throw new Error(
      'Add genres (e.g. country, edm) and/or anchor artist Spotify IDs.'
    )
  }

  let playlistId = storedPlaylistId
  const playlist = await findOwnedPlaylist(userId, playlistId, accessToken)

  if (!playlist || !(await playlistExistsInLibrary(playlistId!, accessToken))) {
    playlistId = await createDiscoverPlaylist(userId, accessToken)
  }

  const known = knownArtistIds ?? new Set<string>()

  const { uris, artistCount, targetGenres } = await pickPlaylistFromNicheArtists(
    options,
    known,
    market,
    accessToken
  )

  await replacePlaylistTracks(playlistId!, uris, accessToken)

  const updated = await spotifyFetch<SpotifyPlaylist>(
    `/playlists/${playlistId}`,
    accessToken
  )
  return {
    playlistId: playlistId!,
    trackCount: Math.min(uris.length, PLAYLIST_SIZE),
    playlistUrl: updated.external_urls.spotify,
    mode: 'niche-artists',
    artistCount,
    targetGenres,
  }
}
